// Assign a bucket (1/2/3) to a single keyword using Taylor's bucket theory:
// Primary driver is competition count (# of listings on Etsy).
// B1 Visibility: low competition — gets you found fast
// B2 Reach: medium competition — builds your audience
// B3 Bestseller: high competition — big pond, scales you to the top
export function assignBucket(vol, comp) {
  if (vol == null || comp == null || vol < 200) return null;
  if (comp >= 100000) return 3;              // Big pond — Bestseller
  if (comp < 10000 && vol >= 500) return 1; // Low comp, rankable fast — Visibility
  if (vol >= 200) return 2;                 // Mid-range — Reach
  return null;
}

// ─── Keyword text-quality detection ────────────────────────────────────────────
// Keyword-research exports (Everbee/eRank) and pasted chat summaries sometimes
// include tag-combination artifacts alongside real search phrases — stemmed or
// invented word fragments and hyphen-mashed strings generated by combining root
// words, e.g. "gifte-sweatshirt", "giftful crewneck", "mom-shirts-giftful",
// "90snostalgia". A real recorded Etsy search query is space-separated; these
// are not. They're still fine to use as Etsy tags, so isLowQualityKeyword()
// flags them for tags_only (deprioritized) rather than discarding them outright.
// Common niche stems seen with a stray trailing "e" glued on (gift→gifte,
// day→daye, shirt→shirte…) — a stem list scales better than hardcoding every
// mutated form; add a stem here to cover its "+e" variant automatically.
const SUSPECT_STEMS = ['gift', 'day', 'shirt', 'tshirt', 'mom', 'dad', 'book', 'read'];
const STEM_E_RE = new RegExp(`\\b(?:${SUSPECT_STEMS.join('|')})e\\b`, 'i');
const INVENTED_WORD_RE = /\b(giftful|momful|funni|sarcastive)\b/i;
const FUL_WHITELIST_RE = /^(beautiful|wonderful|colorful|colourful|grateful|thankful|playful|joyful|cheerful|powerful|helpful|mindful|peaceful|graceful|useful|careful|harmful|hopeful|tasteful|meaningful|delightful|insightful|faithful|youthful|truthful|skillful|skilful|artful|fanciful|blissful|successful|stressful|resourceful|wishful|dutiful|awful|lawful|sinful|willful|restful|doubtful|dreadful|fruitful|masterful|merciful|plentiful|purposeful|rightful|shameful|tactful|thoughtful|bashful|frightful|pitiful|soulful|wakeful|woeful)$/i;

export function isLowQualityKeyword(keyword) {
  const kw = String(keyword || '').trim().toLowerCase();
  if (!kw) return false;
  // Hyphen/underscore-joined strings — real recorded Etsy search queries are
  // space-separated, not hyphen-mashed.
  if (/[-_]/.test(kw)) return true;
  // Digit fused directly to a word with no space, e.g. "90snostalgia"
  if (/\d[a-z]{3,}/.test(kw)) return true;
  // A common stem with a stray trailing "e" glued on, e.g. "gifte", "daye"
  if (STEM_E_RE.test(kw)) return true;
  // Known stemmed/invented fragments from tag-combination generators
  if (INVENTED_WORD_RE.test(kw)) return true;
  // "-ful" suffix glued onto a stem, outside the common real-word whitelist
  const fulWords = kw.match(/\b\w*ful\b/g) || [];
  if (fulWords.some(w => w.length > 3 && !FUL_WHITELIST_RE.test(w))) return true;
  return false;
}

// Assign buckets to a whole list of keywords.
// Misspelling variants (tags_only) are skipped — they never get a bucket.
// Keywords whose text looks like a low-quality tag-combination artifact are
// force-routed to tags_only instead, regardless of their volume/competition.
export function assignBucketsToList(keywords) {
  return keywords.map(k => {
    if (k.tags_only) return k;
    if (isLowQualityKeyword(k.keyword)) {
      return { ...k, tags_only: true, bucket: null, bucket_source: null };
    }
    const vol  = k.volume      != null ? parseInt(k.volume)      : null;
    const comp = k.competition != null ? parseInt(k.competition) : null;
    const bucket = assignBucket(vol, comp);
    if (bucket == null) return k;
    return { ...k, bucket, bucket_source: k.bucket_source || 'everbee_score' };
  });
}

export const BUCKET_STYLE = {
  1: { bg: 'rgba(124,175,138,0.18)', color: '#2d6b3c', border: 'rgba(124,175,138,0.35)', label: 'B1' },
  2: { bg: 'rgba(220,190,100,0.18)', color: '#6b4a10', border: 'rgba(220,190,100,0.35)', label: 'B2' },
  3: { bg: 'rgba(120,140,200,0.18)', color: '#1e306b', border: 'rgba(120,140,200,0.35)', label: 'B3' },
};

export function BucketBadge({ bucket, style }) {
  if (!bucket) return null;
  const s = BUCKET_STYLE[bucket];
  return (
    <span style={{
      fontSize: '0.6rem', fontWeight: 700, padding: '1px 6px', borderRadius: 10,
      background: s.bg, color: s.color, border: `1px solid ${s.border}`,
      whiteSpace: 'nowrap', letterSpacing: '0.04em', ...style,
    }}>
      {s.label}
    </span>
  );
}

// ─── Phase 19 interpretation badges ─────────────────────────────────────────
// Shared between Research.jsx's Keywords tab and KeywordDetail.jsx so the
// same classification/confidence/status/trend reads identically wherever
// it's shown. Deliberately reuses this codebase's existing 4-color language
// (green/amber/red/neutral, same hex values as scoreColor, the seasonal
// badge, and the stale/aged session badges elsewhere) rather than inventing
// a 5th or 6th color — "calm, not a color-coded wall" per the spec.

export const CLASSIFICATION_STYLE = {
  'Strong Unicorn':          { bg: 'rgba(124,175,138,0.18)', color: '#2d6b3c', border: 'rgba(124,175,138,0.35)' },
  'Emerging Unicorn':        { bg: 'var(--rose-faint)',      color: 'var(--dusty-rose)', border: 'rgba(188,143,143,0.4)' },
  'Evergreen':                { bg: 'rgba(124,175,138,0.18)', color: '#2d6b3c', border: 'rgba(124,175,138,0.35)' },
  'Seasonal':                  { bg: 'rgba(232,168,124,0.2)',  color: '#7a4a1e', border: 'rgba(232,168,124,0.4)' },
  'Watchlist':                 { bg: 'rgba(43,41,38,0.08)',    color: 'var(--charcoal-soft)', border: 'rgba(43,41,38,0.15)' },
  'Suspect / Low Confidence': { bg: 'rgba(201,123,123,0.15)', color: '#7a2b2b', border: 'rgba(201,123,123,0.35)' },
};

export function ClassificationBadge({ classification, style }) {
  if (!classification) return null;
  const s = CLASSIFICATION_STYLE[classification] || CLASSIFICATION_STYLE.Watchlist;
  return (
    <span style={{
      fontSize: '0.6rem', fontWeight: 700, padding: '1px 6px', borderRadius: 10,
      background: s.bg, color: s.color, border: `1px solid ${s.border}`,
      whiteSpace: 'nowrap', ...style,
    }}>
      {classification}
    </span>
  );
}

const CONFIDENCE_COLOR = { High: '#2d6b3c', Medium: '#7a4a1e', Low: 'var(--charcoal-soft)' };

export function ConfidenceBadge({ confidence, style }) {
  if (!confidence) return null;
  return (
    <span style={{ fontSize: '0.68rem', color: CONFIDENCE_COLOR[confidence] || 'var(--charcoal-soft)', whiteSpace: 'nowrap', ...style }}>
      ● {confidence}
    </span>
  );
}

export const RESEARCH_STATUS_STYLE = {
  'Researching':       { bg: 'rgba(43,41,38,0.08)',    color: 'var(--charcoal-soft)', border: 'rgba(43,41,38,0.15)' },
  'Validated':          { bg: 'rgba(124,175,138,0.18)', color: '#2d6b3c', border: 'rgba(124,175,138,0.35)' },
  'Watch':              { bg: 'rgba(232,168,124,0.2)',  color: '#7a4a1e', border: 'rgba(232,168,124,0.4)' },
  'Create':             { bg: 'var(--rose-faint)',      color: 'var(--dusty-rose)', border: 'rgba(188,143,143,0.4)' },
  'Hold':               { bg: 'rgba(232,168,124,0.15)', color: '#7a4a1e', border: 'rgba(232,168,124,0.3)' },
  'Reject':             { bg: 'rgba(201,123,123,0.15)', color: '#7a2b2b', border: 'rgba(201,123,123,0.35)' },
  'Seasonal — Future':  { bg: 'rgba(232,168,124,0.2)',  color: '#7a4a1e', border: 'rgba(232,168,124,0.4)' },
  'Archived':           { bg: 'rgba(43,41,38,0.05)',    color: 'var(--charcoal-soft)', border: 'rgba(43,41,38,0.1)' },
};

export function StatusBadge({ status, style }) {
  if (!status) return null;
  const s = RESEARCH_STATUS_STYLE[status] || RESEARCH_STATUS_STYLE.Researching;
  return (
    <span style={{
      fontSize: '0.6rem', fontWeight: 600, padding: '1px 6px', borderRadius: 10,
      background: s.bg, color: s.color, border: `1px solid ${s.border}`,
      whiteSpace: 'nowrap', ...style,
    }}>
      {status}
    </span>
  );
}

const TREND_ARROW = { Emerging: '↗', Rising: '↑', Stable: '→', Seasonal: '↻', Peaking: '⤒', Declining: '↓' };

// Renders nothing for 'Unknown'/null rather than a chip reading "Unknown" —
// most keywords won't have enough history for a trend read yet, and a chip
// on every row for that common case would be exactly the "wall" the spec's
// calm-visual-treatment note warns against.
export function TrendIndicator({ trend, style }) {
  const arrow = TREND_ARROW[trend];
  if (!arrow) return null;
  return (
    <span title={`Trend: ${trend}`} style={{ fontSize: '0.72rem', color: 'var(--charcoal-soft)', ...style }}>
      {arrow}
    </span>
  );
}

export function DisagreementFlag({ flag, style }) {
  if (!flag) return null;
  return (
    <span title="Sources disagree on this keyword's demand — see Keyword Detail" style={{ fontSize: '0.65rem', color: '#7a4a1e', ...style }}>
      ⚠
    </span>
  );
}
